# https://jupyterbook.org/customize/config.html
title: "Mingyue's Portfolio"
author: Mingyue Cheng

only_build_toc_files: true
exclude_patterns:
  - .github/*
  - .pytest_cache/*
  - .venv/*

execute:
  execute_notebooks: "auto"

sphinx:
  config:
    myst_heading_anchors: 4
    suppress_warnings: ["mystnb.unknown_mime_type"]